name: sales-order-&-inventory-lite

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
          ignore:
            - ../venv
        - action: rebuild
          path: ./backend/pyproject.toml
    volumes:
      - sales-order-inv-lite_python3-14_venv:/app/venv

volumes:
  sales-order-inv-lite_python3-14_venv:
    driver: local
